-- 14)
SELECT NAME, LASTNAME, EMAIL FROM CUSTOMERS where STATE = 'SP';

-- 15)
SELECT * FROM CAR where STATUS = 'Liberado';

-- 16)
SELECT * FROM CAR where YEAR = 2016;

-- 17)
SELECT  E.ID,
        E.PHONE_NUMBER,
        E.CONTRACT_DATE,
        P.DESCRIPTION FROM EMPLOYEES AS E
       
  INNER JOIN POSITIONS AS P ON (E.POSITION_ID = P.ID);

-- 18)

SELECT  E.ID,
        E.NAME FROM EMPLOYEES AS E
       
    JOIN LOCATIONS AS L ON (E.ID = L.EMPLOYEE_ID)

GROUP BY E.ID, E.NAME

HAVING COUNT(L.ID) >=2;

-- 19)
SELECT  C.ID,
        C.NAME FROM CUSTOMERS AS C
       
    JOIN LOCATIONS AS L ON (C.ID = L.CUSTOMER_ID)

GROUP BY C.ID, C.NAME

HAVING COUNT(L.ID) >=2;


-- 20)
SELECT  L.ID AS 'CÓDIGO',
        C.NAME AS 'CLIENTE',
        CAR.NAME AS 'CARRO',
        E.NAME AS 'FUNCIONÁRIO' FROM LOCATIONS AS L

    INNER JOIN CUSTOMERS AS C ON (L.CUSTOMER_ID = C.ID)
    INNER JOIN EMPLOYEES AS E ON (L.EMPLOYEE_ID = E.ID)
    INNER JOIN CAR ON (L.CAR_ID = CAR.ID);

-- 21)
SELECT COUNT(ID) AS 'TOTAL' FROM LOCATIONS;

-- 22)
SELECT MAX(TOTAL) AS 'TOTAL MAIOR' FROM LOCATIONS;

-- 23)
SELECT * FROM LOCATIONS WHERE START_DATE >= '2022-05-20' AND 
END_DATE <= '2022-12-25';

SELECT * from LOCATIONS
